MONEY_OK = 0
MONEY_USER_NOT_FOUND = "MONEY_USER_NOT_FOUND"
MONEY_ACC_NOT_FOUND = "MONEY_ACC_NOT_FOUND"
MONEY_BLOCKED = "MONEY_BLOCKED"
MONEY_NO_FUNDS = "MONEY_NO_FUNDS"
MONEY_BAD_AMOUNT = "MONEY_BAD_AMOUNT"
MONEY_INTERNAL_ERROR = "MONEY_INTERNAL_ERROR"

SQL_OK = 0
SQL_CONN_ERROR = "SQL_CONN_ERROR"
SQL_NOT_FOUND = "SQL_NOT_FOUND"
SQL_ALREADY_EXISTS = "SQL_ALREADY_EXISTS"
SQL_INTERNAL_ERROR = "SQL_INTERNAL_ERROR"